### PR TITLE
lab4 grading

### PR DESCRIPTION
**Pull request by legionheir90**
Feeling confident with my code, but not on the new way of pushing work. Did I do this properly?

### CODE REVIEW

**Comment by AnthonyW90** [comment]
Looks like you created a pull request successfully however I do not see a commit from you. Did you push your code?

**Comment by legionheir90** [comment]
I thought I had pushed the content but it is possible that I have not. I will do it again to be sure.

(edit): It says that everything is up to date when I try to push this lab.

**Comment by legionheir90** [comment]
It also will not allow me to create another pull request for lab5 which I just submitted/pushed???

**Comment by AnthonyW90** [comment]
Looks like you are trying to push directly into main. You should be working on the branch with your name.

**Pull request merged**
