### PR TITLE
add mob emoticon_generator.py

### PR DESCRIPTION
**Pull request by smdavis14**
mob emoticon_generator

### CODE REVIEW

**Comment by smdavis14** [comment]
adding loops practice

**Comment by smdavis14** [comment]
Adding rock_paper_scissors

**Comment by smdavis14** [comment]
Had to create another rock_paper_scissors.py to use as a module with 5-rock_paper_scissorsV2.py.  The import didn't like the 5- at the front.

**Comment by smdavis14** [comment]
Added rock, paper, scissors, lizard, spock

**Review by AnthonyW90 — APPROVED** [review]
Love the unicode characters on your rock paper scissors lab

**Pull request merged**
